// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// readMatrixFromZip
NumericMatrix readMatrixFromZip(const std::string& theZipFile, const std::string& theMatrixFile);
RcppExport SEXP ReadMatrixRcpp_readMatrixFromZip(SEXP theZipFileSEXP, SEXP theMatrixFileSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string& >::type theZipFile(theZipFileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type theMatrixFile(theMatrixFileSEXP);
    __result = Rcpp::wrap(readMatrixFromZip(theZipFile, theMatrixFile));
    return __result;
END_RCPP
}
